# Generated by Django 3.2 on 2021-06-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.TextField()),
                ('checked', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
